# Generated by Django 3.1.4 on 2020-12-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0002_auto_20201202_1109'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
